pipeline:
  run-one:
    image: busybox
    group: first
    commands:
      - echo "first run"

  run-two:
    image: busybox
    group: first
    commands:
      - echo "second run.."

  run-three:
    image: ubuntu
    commands:
      - echo "This is a test"
when:
  branch:
    include: [ master, release/* ]
